"""Capabilities that write into the vault notebook.

Named `notebook` rather than `vault` for the reason the vault's own index note
gives: it is *"the notebook, not the instrument."* These capabilities move
finished machine results into the place where the reasoning lives.
"""
from __future__ import annotations

from ..core.capability import Param, capability
from ..vault import sync


def _markdown_table(table, limit: int = 24) -> str:
    columns = list(table.colnames)
    head = "| " + " | ".join(columns) + " |"
    rule = "|" + "|".join("---" for _ in columns) + "|"
    rows = []
    for index in range(min(len(table), limit)):
        cells = []
        for name in columns:
            value = table[name][index]
            if isinstance(value, float):
                cells.append(f"{value:.6g}")
            else:
                cells.append(str(value)[:40])
        rows.append("| " + " | ".join(cells) + " |")
    tail = (f"\n\n*(showing {limit} of {len(table)} rows)*"
            if len(table) > limit else "")
    return "\n".join([head, rule, *rows]) + tail


@capability(
    name="notebook.status", kind="data", wing="theory", cost="free",
    params={},
    summary="Is a vault reachable, and what claims does it hold?",
)
def notebook_status(ctx):
    root = sync.vault_root()
    studies = sync.read_studies_safe()
    payload = {
        "available": sync.available(),
        "vault": str(root) if root else None,
        "astronomy": str(sync.astronomy_dir()) if sync.available() else None,
        "observables": sorted(studies),
    }
    return ctx.data(payload, label=("vault ready" if payload["available"]
                                    else "no vault configured"))


@capability(
    name="notebook.publish", kind="data", wing="theory", cost="free",
    params={"artifact": Param("artifact"), "kind": Param("enum", "auto",
                                                         ("auto", "object", "field", "run")),
            "dry_run": Param("bool", False)},
    summary="Write a finished artifact into the notebook, with its provenance.",
)
def notebook_publish(ctx, artifact, kind, dry_run):
    path = sync.publish_artifact(ctx.kernel, artifact, kind=kind, dry_run=dry_run)
    ctx.note(f"{'would write' if dry_run else 'wrote'} {path}")
    return ctx.data({"path": str(path), "artifact": artifact, "dry_run": dry_run},
                    label=f"→ {path.name}")


@capability(
    name="notebook.sync_study", kind="data", wing="theory", cost="free",
    params={"study": Param("str"), "surface": Param("str", "",
                                                    help="surface artifact; blank = latest"),
            "verdict": Param("str", ""), "dry_run": Param("bool", False)},
    summary="Write a study's results back to its Observables note.",
)
def notebook_sync_study(ctx, study, surface, verdict, dry_run):
    """Frontmatter + one fenced block. The claim, the prose and the reasoning
    stay exactly as Leon wrote them; only machine facts move."""
    if surface:
        art = ctx.artifact(surface)
    else:
        matches = [a for a in ctx.ledger.search(cap="study.run", limit=200)
                   if a.meta.get("study_id") == study]
        art = matches[0] if matches else None
    if art is None:
        raise LookupError(f"no study.run surface for {study!r} — run it first")

    table = ctx.load(art.id)
    meta = art.meta
    updates = {
        "celestrium_last_run": art.created,
        "celestrium_surface": art.id,
        "celestrium_prereg": meta.get("prereg", ""),
        "celestrium_runs": meta.get("combinations", len(table)),
        "celestrium_metric": meta.get("metric", ""),
    }
    if meta.get("succeeded"):
        updates["status"] = "tested"
    if meta.get("metric_min") is not None:
        updates["celestrium_metric_range"] = (
            f"{meta['metric_min']:.6g} … {meta['metric_max']:.6g}")
    if verdict:
        updates["verdict"] = verdict

    block = "\n".join([
        f"### Celestrium results — {art.created}",
        "",
        f"Surface `{art.id}` · metric **{meta.get('metric', '?')}** · "
        f"{meta.get('succeeded', 0)}/{meta.get('combinations', 0)} runs succeeded "
        f"· preregistered analysis `{meta.get('prereg', '—')}`.",
        "",
        _markdown_table(table),
        "",
        "*Generated by Celestrium. Everything outside this block is yours; "
        "re-running the study rewrites only what is inside it.*",
    ])

    path = sync.update_observable(study, updates, block=block, dry_run=dry_run)
    if path is None:
        raise LookupError(f"no Observables note with id: {study}")
    ctx.note(f"{'would update' if dry_run else 'updated'} {path.name}")
    return ctx.data({"study": study, "note": str(path), "surface": art.id,
                     "updates": updates, "dry_run": dry_run},
                    label=f"synced {study} → {path.name}")


@capability(
    name="notebook.log", kind="data", wing="theory", cost="free",
    params={"artifact": Param("artifact"), "title": Param("str", ""),
            "dry_run": Param("bool", False)},
    summary="Append a run log to the notebook (reasoning sections left blank).",
)
def notebook_log(ctx, artifact, title, dry_run):
    art = ctx.artifact(artifact)
    if art is None:
        raise KeyError(f"no artifact {artifact!r}")
    embed = ""
    if art.kind in ("image", "figure", "spectrum"):
        name = sync.copy_figure(art, dry_run=dry_run)
        if name:
            embed = f"\n![[{name}]]\n"
    facts = [f"`{art.cap}` produced a **{art.kind}** artifact `{art.id}`."]
    for key in ("nrows", "combinations", "succeeded", "amplitude", "significance",
                "sky_fraction", "prereg"):
        if key in art.meta:
            facts.append(f"- **{key}**: {art.meta[key]}")
    path = sync.log_run(
        title=title or art.label or art.cap, study=art.study, artifact_id=art.id,
        cap=art.cap, summary="\n".join(facts),
        body=embed + "\n## Provenance\n\n" + ctx.kernel.methods(art.id),
        dry_run=dry_run)
    ctx.note(f"{'would write' if dry_run else 'wrote'} {path}")
    return ctx.data({"path": str(path), "artifact": art.id, "dry_run": dry_run},
                    label=f"→ {path.name}")
